### ISSUE TITLE
投稿の削除依頼ボタンの実装

### ISSUE THREAD

**Issue by Uni-21** [nam-club/ratee_front#2]
投稿の通報＋重複した投稿の削除のため。

どのユーザでも削除依頼ボタンを押せる

・禁止ワードなどが含まれた投稿を削除
・通報に該当するならユーザに1週間くらい投稿させなくする

依頼時には削除依頼理由を選択
・不快な内容が含まれている
・アンケートとして成立していないため（投稿内容が「あああ」とか）
・他の投稿と内容が重複しているため
・その他

**Comment by aoking1213** [comment]
通報ボタンをアンケート詳細画面の最下部に配置する
