### ISSUE TITLE
回答してもリロードしないと反映されない

### ISSUE THREAD

**Issue by Uni-21** [nam-club/ratee_front#49]
### エラー内容
以下の流れでエラーが発生  
  
1. アンケート一覧を開く
2. アンケートに回答
    1. この時点でステータスコード201が返されており、回答は完了している状態
3. 画面上は更新されていないので再度回答ボタンを押すと、既に回答済みのため400エラーが返される
4. リロードをすると回答済みの表示になる

  
https://github.com/nam-club/ratee_front/assets/51052544/dc24b93f-8d28-47c5-83b3-e0f5bde75319
  
### 再現環境
- ローカルにて、コミット 077768f 時点のコードを`npm run dev`で起動  
- PCサイト表示でも発生
- 複数回答可能なアンケートでも発生
- （確か）work環境（netlifyにデプロイ）でも発生

**Comment by aoking1213** [comment]
アンケート回答のcode, messageのreturnし忘れでした。
