### ISSUE TITLE
アンケート作成後、作成されたアンケートの詳細ページに移動する

### ISSUE THREAD

**Issue by Uni-21** [nam-club/ratee_front#50]
今は回答完了後、アンケート作成ページに留まってしまう様子。  
作成後はアンケート詳細ページに移動するのがUX的に良さそう  
  
https://github.com/nam-club/ratee_front/assets/51052544/2014e2da-0423-44bf-8c0b-dec2f4b8a8a9

### 再現環境
- ローカルにて、コミット https://github.com/nam-club/ratee_front/commit/077768ffc530e08c5bd77d2a78b7704c2d856d08 時点のコードをnpm run devで起動

**Comment by aoking1213** [comment]
エラーコード対応をした時に、返り値をうまく子コンポーネントに渡せなくなっていたのが原因でした。

**Comment by aoking1213** [comment]
エラーコード対応をした時に、返り値をうまく子コンポーネントに渡せなくなっていたのが原因でした。
