### ISSUE TITLE
コメント欄の微調整

### ISSUE THREAD

**Issue by Uni-21** [nam-club/ratee_front#67]
添付の画像の通り以下の問題がある。
暇な時に修正頼んます🙏
- IDがundefinedになっている
- 時間表記がISO8601形式（[参考](https://zenn.dev/pixiv/articles/23b726da2236cd)）
  - バックエンドはフロントでの見せ方に関わらず日時はISO8601表記で統一し、フロントでよしなに表示を変える、とすると良いのかなと思っている
<img width="489" alt="スクリーンショット 2024-08-12 0 01 34" src="https://github.com/user-attachments/assets/de745008-13bd-4a9f-a04e-129da419cbe2">

**Comment by aoking1213** [comment]
IDは表示しました。

**Comment by Uni-21** [comment]
時間表記はバックエンドで修正
